name: deepfoldrna
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - pip:
      - biopython==1.79
      - numpy==1.21.2
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - git+https://github.com/NVIDIA/dllogger.git
  - pytorch::pytorch=1.10.*
  - conda-forge::python=3.7
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::pdbfixer
